#!/usr/bin/env bash
# install.sh — Wire agent-toolkit skills into your project
#
# Usage:
#   ./install.sh [adapter] [target-path]
#
# Adapters:
#   cursor    — Symlinks each skill into .cursor/rules/<category>-<slug>.mdc
#   windsurf  — Concatenates all skills into .windsurfrules
#   claude    — Runs adapters/claude/build.js → .claude/CLAUDE.md
#   copilot   — Runs adapters/copilot/build.js → .github/copilot-instructions.md
#   all       — Runs all four adapters
#
# Examples:
#   ./install.sh all .
#   ./install.sh cursor ~/my-project
#   ./install.sh claude ~/my-project

set -euo pipefail

ADAPTER="${1:-all}"
TARGET="${2:-.}"
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REGISTRY="${ROOT}/registry.json"

# ── helpers ─────────────────────────────────────────────────────────────────

die()  { echo "ERROR: $*" >&2; exit 1; }
info() { echo "  → $*"; }

require_node() {
  command -v node >/dev/null 2>&1 || die "Node.js ≥18 is required for this adapter."
  local ver
  ver=$(node -e "process.stdout.write(process.version)" | sed 's/v//')
  local major="${ver%%.*}"
  [[ "$major" -ge 18 ]] || die "Node.js ≥18 required (found v${ver})."
}

require_jq_or_node() {
  command -v node >/dev/null 2>&1 || die "Node.js is required to read registry.json."
}

# Read registry and iterate skills via node (no jq dependency)
each_skill() {
  # Outputs lines of: <category> <slug> <path>
  node - "${REGISTRY}" <<'EOF'
const fs = require('fs');
const reg = JSON.parse(fs.readFileSync(process.argv[1], 'utf8'));
reg.skills.forEach(s => {
  const parts = s.id.split('/');
  console.log([parts[0], parts[1], s.path].join('\t'));
});
EOF
}

strip_frontmatter() {
  # Strip YAML frontmatter from a skill file
  node - "$1" <<'EOF'
const fs = require('fs');
const raw = fs.readFileSync(process.argv[1], 'utf8');
process.stdout.write(raw.replace(/^---[\s\S]*?---\n+/, '').trimStart());
EOF
}

skill_name() {
  node - "${REGISTRY}" "$1" <<'EOF'
const fs = require('fs');
const reg = JSON.parse(fs.readFileSync(process.argv[1], 'utf8'));
const id = process.argv[2];
const skill = reg.skills.find(s => s.id === id);
if (skill) process.stdout.write(skill.name);
EOF
}

# ── adapters ────────────────────────────────────────────────────────────────

install_cursor() {
  echo "▶ cursor → ${TARGET}/.cursor/rules/"
  require_jq_or_node

  local rules_dir="${TARGET}/.cursor/rules"
  mkdir -p "${rules_dir}"

  while IFS=$'\t' read -r category slug skill_path; do
    local src="${ROOT}/${skill_path}"
    local dest="${rules_dir}/${category}-${slug}.mdc"

    if [[ ! -f "${src}" ]]; then
      echo "  WARN: Skill file not found, skipping: ${src}"
      continue
    fi

    # .mdc files are markdown with optional YAML frontmatter — symlink the .md directly
    ln -sf "${src}" "${dest}"
    info "Symlinked: ${dest} → ${src}"
  done < <(each_skill)

  echo "  Done."
}

install_windsurf() {
  echo "▶ windsurf → ${TARGET}/.windsurfrules"
  require_jq_or_node

  local output="${TARGET}/.windsurfrules"
  local version
  version=$(node -e "const r=require('${REGISTRY}');process.stdout.write(r.version)")

  {
    echo "# Agent Skills"
    echo ""
    echo "<!-- Generated by agent-toolkit v${version}. Do not edit directly. -->"
    echo ""

    local first=true
    while IFS=$'\t' read -r category slug skill_path; do
      local src="${ROOT}/${skill_path}"

      if [[ ! -f "${src}" ]]; then
        echo "  WARN: Skill file not found, skipping: ${src}" >&2
        continue
      fi

      [[ "${first}" == true ]] || echo "" && echo "---" && echo ""
      first=false

      local name
      name=$(skill_name "${category}/${slug}")
      echo "## ${name}"
      echo ""
      strip_frontmatter "${src}"
    done < <(each_skill)
  } > "${output}"

  info "Written: ${output}"
  echo "  Done."
}

install_claude() {
  echo "▶ claude → ${TARGET}/.claude/CLAUDE.md"
  require_node
  node "${ROOT}/adapters/claude/build.js" "--target=${TARGET}"
  echo "  Done."
}

install_copilot() {
  echo "▶ copilot → ${TARGET}/.github/copilot-instructions.md"
  require_node
  node "${ROOT}/adapters/copilot/build.js" "--target=${TARGET}"
  echo "  Done."
}

# ── main ────────────────────────────────────────────────────────────────────

[[ -f "${REGISTRY}" ]] || die "registry.json not found at ${REGISTRY}"
[[ -d "${TARGET}" ]]   || die "Target directory does not exist: ${TARGET}"

TARGET="$(cd "${TARGET}" && pwd)"  # resolve to absolute path

echo "agent-toolkit installer"
echo "  Adapter : ${ADAPTER}"
echo "  Target  : ${TARGET}"
echo ""

case "${ADAPTER}" in
  cursor)    install_cursor ;;
  windsurf)  install_windsurf ;;
  claude)    install_claude ;;
  copilot)   install_copilot ;;
  all)
    install_cursor
    install_windsurf
    install_claude
    install_copilot
    ;;
  *)
    die "Unknown adapter '${ADAPTER}'. Valid options: cursor | windsurf | claude | copilot | all"
    ;;
esac

echo ""
echo "✓ Installation complete."
