#!/usr/bin/env node
/**
 * adapters/copilot/build.js
 * Concatenates skill files from registry.json into .github/copilot-instructions.md
 *
 * Usage:
 *   node adapters/copilot/build.js [--target=<path>] [--filter=category:<name>]
 *
 * Options:
 *   --target=<path>          Directory to write .github/copilot-instructions.md into (default: cwd)
 *   --filter=category:<name> Only include skills from this category
 */

'use strict';

const fs = require('fs');
const path = require('path');

const args = process.argv.slice(2);
const targetArg = args.find(a => a.startsWith('--target='));
const filterArg = args.find(a => a.startsWith('--filter='));

const targetDir = targetArg ? path.resolve(targetArg.split('=')[1]) : process.cwd();
const filterCategory = filterArg ? filterArg.split('=')[1].replace('category:', '') : null;

const rootDir = path.resolve(__dirname, '../..');
const registryPath = path.join(rootDir, 'registry.json');

if (!fs.existsSync(registryPath)) {
  console.error(`ERROR: registry.json not found at ${registryPath}`);
  process.exit(1);
}

const registry = JSON.parse(fs.readFileSync(registryPath, 'utf8'));

const skills = filterCategory
  ? registry.skills.filter(s => s.category === filterCategory)
  : registry.skills;

if (skills.length === 0) {
  console.error(`ERROR: No skills found${filterCategory ? ` for category "${filterCategory}"` : ''}`);
  process.exit(1);
}

const outputDir = path.join(targetDir, '.github');
if (!fs.existsSync(outputDir)) {
  fs.mkdirSync(outputDir, { recursive: true });
}

const outputPath = path.join(outputDir, 'copilot-instructions.md');

const header = [
  '# Copilot Instructions',
  '',
  `<!-- Generated by agent-toolkit v${registry.version}. Do not edit directly. -->`,
  `<!-- Source: ${registryPath} -->`,
  `<!-- Skills: ${skills.length} -->`,
  '',
].join('\n');

const sections = skills.map(skill => {
  const filePath = path.join(rootDir, skill.path);

  if (!fs.existsSync(filePath)) {
    console.warn(`WARN: Skill file not found, skipping: ${filePath}`);
    return null;
  }

  const raw = fs.readFileSync(filePath, 'utf8');
  // Strip YAML frontmatter (--- ... ---)
  const body = raw.replace(/^---[\s\S]*?---\n+/, '').trim();

  return `## ${skill.name}\n\n${body}`;
}).filter(Boolean);

const output = header + sections.join('\n\n---\n\n') + '\n';

fs.writeFileSync(outputPath, output, 'utf8');
console.log(`Written: ${outputPath} (${sections.length} skills)`);
